# TACO_CLASS -> (UTD_ELEMENT, UTD_MATERIAL)
mapping = {
    'aluminium foil' : ('sheet', 'aluminum'),
    'battery' : ('battery', ''),
    'aluminium blister pack' : ('pill sheet', None),
    'carded blister pack' : ('pill sheet', None),
    'other plastic bottle' : ('bottle', 'plastic'),
    'clear plastic bottle' : ('bottle', 'plastic'),
    'glass bottle' : ('bottle', 'glass'),
    'plastic bottle cap' : ('bottlecap', 'plastic'),
    'metal bottle cap' : ('bottlecap', 'metal'),
    'broken glass' : ('broken glass', 'glass'),
    'food can' : ('food can', None),
    'aerosol' : ('can', 'metal'),
    'drink can' : ('beverage can', None),
    'toilet tube' : ('toiletpaper roll', 'fiber'),
    'other carton' : ('carton', None),
    'egg carton' : ('egg carton', None),
    'drink carton' : ('carton', 'plastic'),
    'corrugated carton' : ('carton', 'fiber'),
    'meal carton' : ('carton', 'plastic'),
    'pizza box' : ('pizza box', 'cardboard'),
    'paper cup' : ('cup', 'paper'),
    'disposable plastic cup' : ('cup', 'plastic'),
    'foam cup' : ('cup', 'foam'),
    'glass cup' : ('cup', 'glass'),
    'other plastic cup' : ('cup', 'plastic'),
    'food waste' : ('food', 'compostable'),
    'glass jar' : ('jar', 'glass'),
    'plastic lid' : ('lid', 'plastic'),
    'metal lid' : ('lid', 'metal'),
    'other plastic' : (None, 'plastic'),
    'magazine paper' : ('magazine', 'paper'),
    'tissues' : ('tissue', 'fiber'),
    'wrapping paper' : (None, 'paper'),
    'normal paper' : ('sheet', 'paper'),
    'paper bag' : ('bag', 'paper'),
    'plastified paper bag' : ('bag', 'plastic'),
    'plastic film' : ('sheet', 'plastic'),
    'six pack rings' : ('default', 'plastic'),
    'garbage bag' : ('garbage bag', 'plastic'),
    'other plastic wrapper' : ('wrapper', 'plastic'),
    'single-use carrier bag' : ('bag', 'plastic'),
    'polypropylene bag' : ('bag', 'polypropylene'),
    'crisp packet' : ('packet', 'plastic'),
    'spread tub' : ('container', 'plastic'),
    'tupperware' : ('container', 'plastic'),
    'disposable food container' : ('container', 'plastic'),
    'foam food container' : ('container', 'foam'),
    'other plastic container' : ('container', 'plastic'),
    'plastic glooves' : ('glove', 'plastic'),
    'plastic utensils' : ('utensil', 'plastic'),
    'pop tab' : ('pop top', 'aluminum'),
    'rope & strings' : ('rope', None),
    'scrap metal' : (None, 'metal'),
    'shoe' : ('shoe', None),
    'squeezable tube' : ('tube', 'plastic'),
    'plastic straw' : ('straw', 'plastic'),
    'paper straw' : ('straw', 'paper'),
    'styrofoam piece' : (None, None),
    'unlabeled litter' : ('misc', None),
    'cigarette' : ('cigarette', 'trash')
}